### ISSUE TITLE
開発環境のOSについて

### ISSUE THREAD

**Issue by DAIKI-NUMATA** [AutomotiveAIChallenge/aichallenge2023-sim#10]
お世話になっております。

インテグレーション大会の開発環境について質問があるのですが。
ホームページ上にはUbuntu22.04 とありますが、githubのaichallenge2022-simでは20.04となってます。
現在Ubuntu20.04を使用しておりますが、22.04へのアップデートは必要でしょうか？

よろしくお願いいたします。

**Comment by Reee009876** [comment]
お世話になっております。
運営です。

> インテグレーション大会の開発環境について質問があるのですが。
ホームページ上にはUbuntu22.04 とありますが、githubのaichallenge2022-simでは20.04となってます。
2022-sim時点でのAWSIMの対象OSは20.04だったのですが、現時点(2023-sim)での対象は22.04となっているため、引き上げております。

> 現在Ubuntu20.04を使用しておりますが、22.04へのアップデートは必要でしょうか？
22.04がサポート対象となるため、引き上げを推奨しております。
※運営側の環境も22.04となっております。

よろしくお願いします。

**Comment by Reee009876** [comment]
@DAIKI-NUMATA 
こちらいかがでしょうか？
解決した場合はお手数ですが、closeをお願いします。
