### ISSUE TITLE
AutowareがErrorで起動しない

### ISSUE THREAD

**Issue by hidechun** [AutomotiveAIChallenge/aichallenge2023-sim#11]
事務局の皆様　参加者の皆様
お世話になっております。

https://automotiveaichallenge.github.io/aichallenge2023-sim/setup/
こちらの手順にしたがって、動作確認を実施しておりますが、Autowareが起動しません。

https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/issues/7
こちらの方と同一案件かもしれませんが、Logを共有いたしますのでご確認頂けませんでしょうか。

■Install状況
docker　→　済
rocker　→　済
Nvidia Container Toolkit　→　済
git lfs　→　済
ROS2 (動画確認済バージョン: Humble)　→　済
Dockerイメージの準備・起動 〜 Autowareの準備

Dockerイメージを入手は以下の手法で実施
＞※上記の方法では長時間かかってしまう方・タイムアウトしてしまう方↓
＞[こちら](https://drive.google.com/file/d/1mOEpiN36UPe70NqiibloDcd_ewgMr_5P/view?usp=sharing)に、イメージをtarにまとめたも＞のを置きましたので、下記コマンドよりご利用ください
＞docker load < autoware-universe-cuda_v1.tar.gz

■動作状況
◆AWSIMの起動（Log230625_AWSIM.txt　→　AWSIMは起動します）
１：大会用の実行ファイルを[ダウンロード](https://drive.google.com/file/d/1aduBKhYGI0mhhRbgu4B05pBTyFXcZsGN/view?usp=sharing)し、解凍 ※チュートリアル用
２：上記ファイルを以下に配置
    aichallenge2023-sim/autoware内に大会用AWSIM実行ファイルを展開(以下、aichallenge2023-sim/autoware/AWSIM/AWSIM.x86_64に配置されているものとします。)
３：ターミナル１を開き　rockerを起動 
[Log230625_AWSIM.txt](https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/files/11859356/Log230625_AWSIM.txt)

◆Autowareの起動（Log230625_Autoware.txt　→　ターミナルの処理がErrorで進まなくなります）
１：ターミナル２を起動
２：rockerを起動 
３：コンテナ内で以下を実行
 export ROS_LOCALHOST_ONLY=1
 export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
 export RCUTILS_COLORIZED_OUTPUT=1
 source /autoware/install/setup.bash
 /aichallenge/AWSIM/AWSIM.x86_64

４：ターミナルの処理がErrorで進まなくなります
[Log230625_Autoware.txt](https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/files/11859357/Log230625_Autoware.txt)

■当方のPC-SPEC
　Hardware
　 ・CPU:i7-11800H
　 ・RAM:DDR4 32GB
　 ・ROM:SSD 512GB
　 ・GTX-3060laptop 6GB
　Software
　 ・Ubuntu 22.04
　 ・Ros2 Humble

**Comment by uhobeike** [comment]
@hidechun 
以下を実行するとどうでしょうか？
```
sudo sysctl -w net.core.rmem_max=2147483647
sudo ip link set multicast on lo
```

**Comment by hidechun** [comment]
@uhobeike さん
Rvizが立ち上がりました。お力添え頂きありがとうございます。
起動時のLogを添付いたします。

差し支えなければ、簡単で構いませんので
　・Errorの原因
　・上記でなぜ解決できたのか
を教えて頂ければ幸いです。学習の足がかりとして役立てたいと考えております。

[Log230625_2_AWSIM.txt](https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/files/11859723/Log230625_2_AWSIM.txt)
[Log230625_2_Autoware.txt](https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/files/11859724/Log230625_2_Autoware.txt)

**Comment by hidechun** [comment]
問題自体は解決したようなので、ISSUEはCloseいたします。

**Comment by taikitanaka3** [comment]
@hidechun 
local host がデフォルトでmulticastをサポートしていないため、local host onlyの設定にしたらsudo ip link set multicast on loを実行する必要があるようです。

```
export ROS_LOCALHOST_ONLY=1
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
をしたあとに
sudo ip link set multicast on lo
をしないと

[INFO] [launch]: All log files can be found below /root/.ros/log/2023-06-25-17-52-53-045333-hidechun43-LAPKC71E-131
[INFO] [launch]: Default logging verbosity is set to INFO
1687683179.931122 [0]       ros2: selected interface "lo" is not multicast-capable: disabling multicast

こちらのログでErrorになるのはなぜですか？
```

ChatGPT
このエラーは、ローカルホスト(lo)がマルチキャストをサポートしていないことを示しています。マルチキャストとは、単一のソースから複数の宛先へデータを一度に送信する通信方法の一つです。

ロボット操作システム(ROS)の実装では、ROS 2を使用している場合、特にDDS(Distributed Data Service)ミドルウェアを使用している場合、このマルチキャスト通信が重要となる場合があります。DDSミドルウェアは、リアルタイムの大規模分散システムをサポートするための通信プロトコルで、一部の機能（例えば、データの発見）ではマルチキャストを使用します。

あなたが設定した環境変数ROS_LOCALHOST_ONLY=1は、ROS 2がlocalhost（つまり、同じマシン上のプロセス間）でのみ通信するように設定します。これは、ネットワーク上の他のマシンからの接続を防ぐための一般的な手法です。

一方で、RMW_IMPLEMENTATION=rmw_cyclonedds_cppは、ROS 2のミドルウェア実装をCyclone DDSに設定します。Cyclone DDSは、マルチキャストを使用してDDSのデータの発見を行います。

したがって、あなたがsudo ip link set multicast on loを実行しなかった場合、ローカルホストはマルチキャストをサポートしない設定となり、Cyclone DDSがマルチキャストを使ってデータの発見を行うことができないため、あなたが見たエラーが発生します。

この問題を解決するためには、ローカルホスト上でマルチキャストを有効にする必要があります。これは、あなたが指示したコマンドsudo ip link set multicast on loを実行することで達成できます。

**Comment by hidechun** [comment]
@taikitanaka3　さん
@uhobeike 　さん
ChatGTP　さんｗ

エラーからDDSのキャスト方式のアンマッチなど想像すらできませんでした・・・。

Setup方法やサンプルコードも変更になったので、気持ちを切り替えてがんばります。
ご教示頂きありがとうございました！
