### ISSUE TITLE
AWSIM is unable to perform reverse operation

### ISSUE THREAD

**Issue by nainaigetuide** [AutomotiveAIChallenge/aichallenge2023-sim#26]
Launch RVIZ2 in Terminal 1.
`ros2 launch aichallenge_launch aichallenge.launch.xml`

Launch AWSIM in Terminal 2.
`./AWSIM/AWSIM.x86_64`

Perform control testing using the ManualController in RVIZ2.
![image](https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/assets/22877692/c99cfd62-9350-43a9-910b-b221ab52d4df)

When I set the target speed to 5 km/h, the car can move forward.

When I set the target speed to -5 km/h, the car stops and cannot move forward normally. 
Inspecting the topic data, the output control commands are normal.
`ros2 topic echo /control/command/control_cmd`
`stamp:
  sec: 874
  nanosec: 959980443
lateral:
  stamp:
    sec: 0
    nanosec: 0
  steering_tire_angle: 0.0
  steering_tire_rotation_rate: 0.0
longitudinal:
  stamp:
    sec: 0
    nanosec: 0
  speed: -1.3888888359069824
  acceleration: 0.6944444179534912
  jerk: 0.0`

Is reverse not allowed in this competition?

**Comment by taikitanaka3** [comment]
@nainaigetuide 
this issue is solved in july please update AWSIM version.
please feel free to reopen this issue if you have farther problem.
