### ISSUE TITLE
There is no documentation on how to create aichallenge_submit.tar.gz

### ISSUE THREAD

**Issue by hir-yk** [AutomotiveAIChallenge/aichallenge2023-sim#30]
The instructions at https://automotiveaichallenge.github.io/aichallenge2023-sim/online/index.html say "手順1で作成したaichallenge_submit.tar.gzを「ファイルを選択」からアップロードしてください", however there is no information on how to create 'aichallenge_submit.tar.gz' in step 1.

**Comment by Reee009876** [comment]
お世話になっております。
運営です。
下記のステップで、aichallenge_submit.tar.gzの作成を行う手順となっております。
<img width="840" alt="image" src="https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/assets/113989589/b814e7e0-dded-4920-9ede-d2e591c86149">

-------
Thank you for your assistance.
This is an operation.

Please follow the steps below to create aichallenge_submit.tar.gz.

**Comment by hir-yk** [comment]
I solved it. I needed to update the repository with 'git pull'. Thank you.
