### ISSUE TITLE
オンライン採点環境へのログインのパスワードの再設定のお願い方法について

### ISSUE THREAD

**Issue by atsuko-kobajp** [AutomotiveAIChallenge/aichallenge2023-sim#34]
ご担当者様
お世話になっております。小林と申します。
遅ればせながらオンライン採点環境へログインしようとしましたが、メールでいただいたIDとパスワードを入力した結果、一時パスワードがエクスパイアしたため、管理者へ連絡してください、というメッセージが表示されてしまいました。お手数をおかけし申し訳ございませんが、パスワードの再設定と再送をお願いしたく、必要な手続きを教えてください。
よろしくお願い致します。

**Comment by hidechun** [comment]
お世話になります。　チーム：ひでちゅん（４３）です。

私も同様の状態となっており、パスワードの再設定もできません。
夏季休暇で巻き返ししてやろう組の方は同様の状態になっているのではないかと思われます。

パスワードの再設定方法について、調査・通達をお願いいたします。

**Comment by Reee009876** [comment]
お世話になっております。
ご連絡が遅くなり、大変申し訳ありません。

ただ今、確認をしております。
もうしばらくお時間をいただきたいです。

**Comment by Reee009876** [comment]
申し訳ありません．
ただいま確認しております．
もう少しだけお待ちください．

**Comment by Reee009876** [comment]
@atsuko-kobajp 
お世話になっております。
大変お待たせいたしました。

チーム名とユーザ名を教えていただけないでしょうか？
再発行いたします。

**Comment by Reee009876** [comment]
@hidechun 
お世話になっております。
大変お待たせいたしました。

再発行メールをお送りいたしましたので、ご確認お願いします。

**Comment by hidechun** [comment]
@Reee009876 さま
Login出来ました。PW_Resetありがとうございます。
本日再発行連絡いただけると信じて、、、明日休暇をねじ込んで良かったｗ

@atsuko-kobajp さま
再Login出来たら本件Closeお願いします。

**Comment by atsuko-kobajp** [comment]
@Reee009876 さま
ありがとうございます。チーム名はPanda,ユーザIDはatsukokobayashiです。お手数おかけし恐れ入りますが再発行をよろしくお願い致します。

**Comment by Reee009876** [comment]
@atsuko-kobajp 
お世話になっております

再発行完了しましたので、メールのご確認をお願いします。

**Comment by Reee009876** [comment]
@atsuko-kobajp 
ログインができましたら、Closeをお願いします

**Comment by atsuko-kobajp** [comment]
ログインできました。ありがとうございます。CLOSE致します。
