### ISSUE TITLE
Lanelet2のcenter_lane_lineの軌道について

### ISSUE THREAD

**Issue by makotoyoshigoe** [AutomotiveAIChallenge/aichallenge2023-sim#39]
現在, 課題3-2に取り組んでいるのですが, 下の写真の赤い丸で囲ったカーブの箇所の経路計画がレーン外に行くようになってしまい, パラメータ調整を行っても改善されません. 
![Screenshot from 2023-08-21 14-29-53](https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/assets/91446273/17107b35-33fb-4b4f-ad85-26b6997b3a95)

原因を調べてみたところ, Lanelet2のcenter_lane_lineの軌道（下の写真）が経路計画の軌道と似ていることがわかりました. 
そこで, 経路計画はcenter_lane_lineに沿って生成されていると予想を立て, center_lane_lineの軌道がレーン外に行くようになっているため経路計画もレーン外に出てしまっていると考えました. 
![Screenshot from 2023-08-21 14-28-07](https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/assets/91446273/1a5e3935-b05c-41af-9ddf-50f16cdb038d)

そこで, 2つ質問があるのですが
1. "経路計画はcenter_lane_lineに沿って生成されている"という予想は正しいでしょうか？
2. center_lane_lineの軌道は写真のような生成のされ方で正しいのでしょうか？

回答よろしくおねがいします.

**Comment by taikitanaka3** [comment]
@makotoyoshigoe 
質問ありがとうございます。
1. ご指摘の通り、経路はcenter lane lineに沿って生成されています。
こちらのパラメータでMapLoaderのパッケージで上書きすることもできますが、現状ハードコードされているため、既存のものを使う場合はこちらをoverwriteLaneletsCenterlineをtrueに書き換えてからpackage名をrenameしてlaunchするなどが必要です。
https://github.com/autowarefoundation/autoware.universe/blob/73b28776680fcee2dc5527a492e46b46a9bfd409/map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp#L79

2. center_lane_lineの軌道
> center_lane_lineの軌道は写真のような生成のされ方で正しいのでしょうか？
もとのlaneletのcenterlineの形状が上記のようになっていますので、単体の動作としては想定通りですが、所望の動作になるような工夫が必要になります。

**Comment by makotoyoshigoe** [comment]
@taikitanaka3 様
返答いただきありがとうございます. 承知いたしました.
