### ISSUE TITLE
Rocker Presence

### ISSUE THREAD

**Issue by RAAA-Alaguvel-Armstrong** [AutomotiveAIChallenge/aichallenge2023-sim#7]
We have installed the rocker command using pip install rocker but we are getting an error, it says -
WARNING unable to detect os for base image 'ghcr.io/automotiveaichallenge/aichallenge2023-sim/', maybe the base image does not exist

**Comment by taikitanaka3** [comment]
@RAAA-Alaguvel-Armstrong 
may be you should try this section first before running container
https://automotiveaichallenge.github.io/aichallenge2023-sim/en/setup/index.html#autoware

**Comment by RAAA-Alaguvel-Armstrong** [comment]
After trying the above link, the following error occurred - RVIZ is not starting

[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/localization/util/crop_box_filter_measurement_range' in container 'pointcloud_container'
[ERROR] [rviz2-70]: process has died [pid 438, exit code -6, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d /aichallenge/aichallenge_ws/install/autoware_launch/share/autoware_launch/rviz/autoware.rviz -s /aichallenge/aichallenge_ws/install/autoware_launch/share/autoware_launch/rviz/image/autoware.png --ros-args -r __node:=rviz2 -p use_sim_time:=True -p wheel_radius:=0.255 -p wheel_width:=0.196 -p wheel_base:=2.14 -p wheel_tread:=0.975 -p front_overhang:=0.467 -p rear_overhang:=0.51 -p left_overhang:=0.145 -p right_overhang:=0.145 -p vehicle_height:=2.2 -p max_steer_angle:=0.64'].

**Comment by taikitanaka3** [comment]
@RAAA-Alaguvel-Armstrong 
can you try this command?
```
sudo ip link set multicast on lo
```

**Comment by RAAA-Alaguvel-Armstrong** [comment]
thank you @taikitanaka3 
using muliticast on now AWSIM and autoware.universe are working.

**Comment by RAAA-Alaguvel-Armstrong** [comment]
thank you, now working
